<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ZKM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Gedmo\Mapping\Annotation as Gedmo;
use DoctrineExtensions\StandardFields\Mapping\Annotation as ZK;

/**
 * Entity class that defines the entity structure and behaviours.
 *
 * This is the base entity class for medium entities.
 *
 * @abstract
 */
abstract class SimpleMedia_Entity_Base_Medium extends Zikula_EntityAccess
{
    /**
     * @var string The tablename this object maps to.
     */
    protected $_objectType = 'medium';
    
    /**
     * @var SimpleMedia_Entity_Validator_Medium The validator for this entity.
     */
    protected $_validator = null;
    
    /**
     * @var boolean Option to bypass validation if needed.
     */
    protected $_bypassValidation = false;
    
    /**
     * @var array List of available item actions.
     */
    protected $_actions = array();
    
    /**
     * @var array The current workflow data of this object.
     */
    protected $__WORKFLOW__ = array();
    
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", unique=true)
     * @var integer $id.
     */
    protected $id = 0;
    
    /**
     * @ORM\Column(length=20)
     * @var string $workflowState.
     */
    protected $workflowState = 'initial';
    
    /**
     * @Gedmo\Sluggable(slugField="slug", position=1)
     * @ORM\Column(length=255)
     * @var string $title.
     */
    protected $title = '';
    
    /**
     * The file meta data array.
     *
     * @ORM\Column(type="array")
     * @var array $theFileMeta.
     */
    protected $theFileMeta = array();
    
    /**
     * @ORM\Column(length=255)
     * @var string $theFile.
     */
    protected $theFile = '';
    
    /**
     * The full path to the the file.
     *
     * @var string $theFileFullPath.
     */
    protected $theFileFullPath = '';
    
    /**
     * Full the file path as url.
     *
     * @var string $theFileFullPathUrl.
     */
    protected $theFileFullPathUrl = '';
    /**
     * @ORM\Column(type="text", length=2000)
     * @var text $description.
     */
    protected $description = '';
    
    /**
     * @ORM\Column(length=15)
     * @var string $zipcode.
     */
    protected $zipcode = '';
    
    /**
     * @ORM\Column(type="bigint")
     * @var integer $previewImage.
     */
    protected $previewImage = 0;
    
    /**
     * @ORM\Column(type="bigint")
     * @var integer $sortValue.
     */
    protected $sortValue = 0;
    
    /**
     * @ORM\Column(length=255)
     * @var string $mediaType.
     */
    protected $mediaType = null;
    
    /**
     * @ORM\Column(type="bigint")
     * @var integer $viewsCount.
     */
    protected $viewsCount = 0;
    
    
    /**
     * The coordinate's latitude part.
     *
     * @ORM\Column(type="decimal", precision=10, scale=7)
     * @var decimal $latitude.
     */
    protected $latitude = 0.00;
    
    /**
     * The coordinate's longitude part.
     *
     * @ORM\Column(type="decimal", precision=10, scale=7)
     * @var decimal $longitude.
     */
    protected $longitude = 0.00;
    
    /**
     * @Gedmo\Slug(style="lower", separator="-", unique=true, updatable=true)
     * @ORM\Column(type="string", length=255, unique=true)
     * @var string $slug.
     */
    protected $slug;
    
    /**
     * @ORM\OneToOne(targetEntity="SimpleMedia_Entity_MediumMetaData", 
     *               mappedBy="entity", cascade={"all"},
     *               orphanRemoval=true)
     * @var SimpleMedia_Entity_MediumMetaData
     */
    protected $metadata = null;
    
    /**
     * @ORM\OneToMany(targetEntity="SimpleMedia_Entity_MediumAttribute", 
     *                mappedBy="entity", cascade={"all"}, 
     *                orphanRemoval=true, indexBy="name")
     * @var SimpleMedia_Entity_MediumAttribute
     */
    protected $attributes = null;
    
    /**
     * @ORM\OneToMany(targetEntity="SimpleMedia_Entity_MediumCategory", 
     *                mappedBy="entity", cascade={"all"}, 
     *                orphanRemoval=true)
     * @var SimpleMedia_Entity_MediumCategory
     */
    protected $categories = null;
    
    /**
     * @ORM\Column(type="integer")
     * @ZK\StandardFields(type="userid", on="create")
     * @var integer $createdUserId.
     */
    protected $createdUserId;
    
    /**
     * @ORM\Column(type="integer")
     * @ZK\StandardFields(type="userid", on="update")
     * @var integer $updatedUserId.
     */
    protected $updatedUserId;
    
    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     * @var datetime $createdDate.
     */
    protected $createdDate;
    
    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     * @var datetime $updatedDate.
     */
    protected $updatedDate;
    
    /**
     * Bidirectional - Many media [media] are linked by one collection [collection] (OWNING SIDE).
     *
     * @ORM\ManyToOne(targetEntity="SimpleMedia_Entity_Collection", inversedBy="media")
     * @ORM\JoinTable(name="simmed_collection",
             *      joinColumns={@ORM\JoinColumn(name="id", referencedColumnName="id" , unique=true, nullable=false)
             },
             *      inverseJoinColumns={@ORM\JoinColumn(name="id", referencedColumnName="id" , unique=true, nullable=false)
            }
             * )
     * @var SimpleMedia_Entity_Collection $collection.
     */
    protected $collection;
    
    
    /**
     * Constructor.
     * Will not be called by Doctrine and can therefore be used
     * for own implementation purposes. It is also possible to add
     * arbitrary arguments as with every other class method.
     *
     * @param TODO
     */
    public function __construct()
    {
        
        $serviceManager = ServiceUtil::getManager();
        $listHelper = new SimpleMedia_Util_ListEntries($serviceManager);
        
        $items = array();
        $listEntries = $listHelper->getMediaTypeEntriesForMedium();
        foreach ($listEntries as $listEntry) {
            if ($listEntry['default'] === true) {
                $items[] = $listEntry['value'];
            }
        }
        $this->mediaType = implode('###', $items);
        
        $this->workflowState = 'initial';
        $this->initValidator();
        $this->initWorkflow();
        $this->attributes = new ArrayCollection();
        $this->categories = new ArrayCollection();
    }
    
    /**
     * Get _object type.
     *
     * @return string
     */
    public function get_objectType()
    {
        return $this->_objectType;
    }
    
    /**
     * Set _object type.
     *
     * @param string $_objectType.
     *
     * @return void
     */
    public function set_objectType($_objectType)
    {
        $this->_objectType = $_objectType;
    }
    
    /**
     * Get _validator.
     *
     * @return SimpleMedia_Entity_Validator_Medium
     */
    public function get_validator()
    {
        return $this->_validator;
    }
    
    /**
     * Set _validator.
     *
     * @param SimpleMedia_Entity_Validator_Medium $_validator.
     *
     * @return void
     */
    public function set_validator(SimpleMedia_Entity_Validator_Medium $_validator = null)
    {
        $this->_validator = $_validator;
    }
    
    /**
     * Get _bypass validation.
     *
     * @return boolean
     */
    public function get_bypassValidation()
    {
        return $this->_bypassValidation;
    }
    
    /**
     * Set _bypass validation.
     *
     * @param boolean $_bypassValidation.
     *
     * @return void
     */
    public function set_bypassValidation($_bypassValidation)
    {
        $this->_bypassValidation = $_bypassValidation;
    }
    
    /**
     * Get _actions.
     *
     * @return array
     */
    public function get_actions()
    {
        return $this->_actions;
    }
    
    /**
     * Set _actions.
     *
     * @param array $_actions.
     *
     * @return void
     */
    public function set_actions(array $_actions = Array())
    {
        $this->_actions = $_actions;
    }
    
    /**
     * Get __ w o r k f l o w__.
     *
     * @return array
     */
    public function get__WORKFLOW__()
    {
        return $this->__WORKFLOW__;
    }
    
    /**
     * Set __ w o r k f l o w__.
     *
     * @param array $__WORKFLOW__.
     *
     * @return void
     */
    public function set__WORKFLOW__(array $__WORKFLOW__ = Array())
    {
        $this->__WORKFLOW__ = $__WORKFLOW__;
    }
    
    
    /**
     * Get id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set id.
     *
     * @param integer $id.
     *
     * @return void
     */
    public function setId($id)
    {
        if ($id != $this->id) {
            $this->id = $id;
        }
    }
    
    /**
     * Get workflow state.
     *
     * @return string
     */
    public function getWorkflowState()
    {
        return $this->workflowState;
    }
    
    /**
     * Set workflow state.
     *
     * @param string $workflowState.
     *
     * @return void
     */
    public function setWorkflowState($workflowState)
    {
        if ($workflowState != $this->workflowState) {
            $this->workflowState = $workflowState;
        }
    }
    
    /**
     * Get title.
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->title;
    }
    
    /**
     * Set title.
     *
     * @param string $title.
     *
     * @return void
     */
    public function setTitle($title)
    {
        if ($title != $this->title) {
            $this->title = $title;
        }
    }
    
    /**
     * Get the file.
     *
     * @return string
     */
    public function getTheFile()
    {
        return $this->theFile;
    }
    
    /**
     * Set the file.
     *
     * @param string $theFile.
     *
     * @return void
     */
    public function setTheFile($theFile)
    {
        if ($theFile != $this->theFile) {
            $this->theFile = $theFile;
        }
    }
    
    /**
     * Get the file full path.
     *
     * @return string
     */
    public function getTheFileFullPath()
    {
        return $this->theFileFullPath;
    }
    
    /**
     * Set the file full path.
     *
     * @param string $theFileFullPath.
     *
     * @return void
     */
    public function setTheFileFullPath($theFileFullPath)
    {
        if ($theFileFullPath != $this->theFileFullPath) {
            $this->theFileFullPath = $theFileFullPath;
        }
    }
    
    /**
     * Get the file full path url.
     *
     * @return string
     */
    public function getTheFileFullPathUrl()
    {
        return $this->theFileFullPathUrl;
    }
    
    /**
     * Set the file full path url.
     *
     * @param string $theFileFullPathUrl.
     *
     * @return void
     */
    public function setTheFileFullPathUrl($theFileFullPathUrl)
    {
        if ($theFileFullPathUrl != $this->theFileFullPathUrl) {
            $this->theFileFullPathUrl = $theFileFullPathUrl;
        }
    }
    
    /**
     * Get the file meta.
     *
     * @return array
     */
    public function getTheFileMeta()
    {
        return $this->theFileMeta;
    }
    
    /**
     * Set the file meta.
     *
     * @param array $theFileMeta.
     *
     * @return void
     */
    public function setTheFileMeta($theFileMeta = Array())
    {
        if ($theFileMeta != $this->theFileMeta) {
            $this->theFileMeta = $theFileMeta;
        }
    }
    
    /**
     * Get description.
     *
     * @return text
     */
    public function getDescription()
    {
        return $this->description;
    }
    
    /**
     * Set description.
     *
     * @param text $description.
     *
     * @return void
     */
    public function setDescription($description)
    {
        if ($description != $this->description) {
            $this->description = $description;
        }
    }
    
    /**
     * Get zipcode.
     *
     * @return string
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }
    
    /**
     * Set zipcode.
     *
     * @param string $zipcode.
     *
     * @return void
     */
    public function setZipcode($zipcode)
    {
        if ($zipcode != $this->zipcode) {
            $this->zipcode = $zipcode;
        }
    }
    
    /**
     * Get preview image.
     *
     * @return bigint
     */
    public function getPreviewImage()
    {
        return $this->previewImage;
    }
    
    /**
     * Set preview image.
     *
     * @param bigint $previewImage.
     *
     * @return void
     */
    public function setPreviewImage($previewImage)
    {
        if ($previewImage != $this->previewImage) {
            $this->previewImage = $previewImage;
        }
    }
    
    /**
     * Get sort value.
     *
     * @return bigint
     */
    public function getSortValue()
    {
        return $this->sortValue;
    }
    
    /**
     * Set sort value.
     *
     * @param bigint $sortValue.
     *
     * @return void
     */
    public function setSortValue($sortValue)
    {
        if ($sortValue != $this->sortValue) {
            $this->sortValue = $sortValue;
        }
    }
    
    /**
     * Get media type.
     *
     * @return string
     */
    public function getMediaType()
    {
        return $this->mediaType;
    }
    
    /**
     * Set media type.
     *
     * @param string $mediaType.
     *
     * @return void
     */
    public function setMediaType($mediaType)
    {
        if ($mediaType != $this->mediaType) {
            $this->mediaType = $mediaType;
        }
    }
    
    /**
     * Get views count.
     *
     * @return bigint
     */
    public function getViewsCount()
    {
        return $this->viewsCount;
    }
    
    /**
     * Set views count.
     *
     * @param bigint $viewsCount.
     *
     * @return void
     */
    public function setViewsCount($viewsCount)
    {
        if ($viewsCount != $this->viewsCount) {
            $this->viewsCount = $viewsCount;
        }
    }
    
    /**
     * Get latitude.
     *
     * @return decimal
     */
    public function getLatitude()
    {
        return $this->latitude;
    }
    
    /**
     * Set latitude.
     *
     * @param decimal $latitude.
     *
     * @return void
     */
    public function setLatitude($latitude)
    {
        $this->latitude = $latitude;
    }
    
    /**
     * Get longitude.
     *
     * @return decimal
     */
    public function getLongitude()
    {
        return $this->longitude;
    }
    
    /**
     * Set longitude.
     *
     * @param decimal $longitude.
     *
     * @return void
     */
    public function setLongitude($longitude)
    {
        $this->longitude = $longitude;
    }
    
    /**
     * Get slug.
     *
     * @return string
     */
    public function getSlug()
    {
        return $this->slug;
    }
    
    /**
     * Get metadata.
     *
     * @return SimpleMedia_Entity_MediumMetaData
     */
    public function getMetadata()
    {
        return $this->metadata;
    }
    
    /**
     * Set metadata.
     *
     * @param SimpleMedia_Entity_MediumMetaData $metadata.
     *
     * @return void
     */
    public function setMetadata(SimpleMedia_Entity_MediumMetaData $metadata = null)
    {
        $this->metadata = $metadata;
    }
    
    /**
     * Get attributes.
     *
     * @return array
     */
    public function getAttributes()
    {
        return $this->attributes;
    }
    
    /**
     * Set attribute.
     *
     * @param string $name.
     * @param string $value.
     *
     * @return void
     */
    public function setAttribute($name, $value)
    {
        if(isset($this->attributes[$name])) {
            if($value == null) {
                $this->attributes->remove($name);
            } else {
                $this->attributes[$name]->setValue($value);
            }
        } else {
            $this->attributes[$name] = new SimpleMedia_Entity_MediumAttribute($name, $value, $this);
        }
    }
    
    /**
     * Get categories.
     *
     * @return array
     */
    public function getCategories()
    {
        return $this->categories;
    }
    
    /**
     * Set categories.
     *
     * @param array $categories.
     *
     * @return void
     */
    public function setCategories($categories)
    {
        $this->categories = $categories;
    }
    
    /**
     * Get created user id.
     *
     * @return integer
     */
    public function getCreatedUserId()
    {
        return $this->createdUserId;
    }
    
    /**
     * Set created user id.
     *
     * @param integer $createdUserId.
     *
     * @return void
     */
    public function setCreatedUserId($createdUserId)
    {
        $this->createdUserId = $createdUserId;
    }
    
    /**
     * Get updated user id.
     *
     * @return integer
     */
    public function getUpdatedUserId()
    {
        return $this->updatedUserId;
    }
    
    /**
     * Set updated user id.
     *
     * @param integer $updatedUserId.
     *
     * @return void
     */
    public function setUpdatedUserId($updatedUserId)
    {
        $this->updatedUserId = $updatedUserId;
    }
    
    /**
     * Get created date.
     *
     * @return datetime
     */
    public function getCreatedDate()
    {
        return $this->createdDate;
    }
    
    /**
     * Set created date.
     *
     * @param datetime $createdDate.
     *
     * @return void
     */
    public function setCreatedDate($createdDate)
    {
        $this->createdDate = $createdDate;
    }
    
    /**
     * Get updated date.
     *
     * @return datetime
     */
    public function getUpdatedDate()
    {
        return $this->updatedDate;
    }
    
    /**
     * Set updated date.
     *
     * @param datetime $updatedDate.
     *
     * @return void
     */
    public function setUpdatedDate($updatedDate)
    {
        $this->updatedDate = $updatedDate;
    }
    
    
    /**
     * Get collection.
     *
     * @return SimpleMedia_Entity_Collection
     */
    public function getCollection()
    {
        return $this->collection;
    }
    
    /**
     * Set collection.
     *
     * @param SimpleMedia_Entity_Collection $collection.
     *
     * @return void
     */
    public function setCollection(SimpleMedia_Entity_Collection $collection = null)
    {
        $this->collection = $collection;
    }
    
    
    /**
     * Initialise validator and return it's instance.
     *
     * @return SimpleMedia_Entity_Validator_Medium The validator for this entity.
     */
    public function initValidator()
    {
        if (!is_null($this->_validator)) {
            return $this->_validator;
        }
        $this->_validator = new SimpleMedia_Entity_Validator_Medium($this);
    
        return $this->_validator;
    }
    
    /**
     * Sets/retrieves the workflow details.
     */
    public function initWorkflow()
    {
        $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
        $isReuse = FormUtil::getPassedValue('astemplate', '', 'GETPOST', FILTER_SANITIZE_STRING);
    
        // apply workflow with most important information
        $idColumn = 'id';
        $workflowHelper = new SimpleMedia_Util_Workflow(ServiceUtil::getManager());
        $schemaName = $workflowHelper->getWorkflowName($this['_objectType']);
        $this['__WORKFLOW__'] = array(
            'state' => $this['workflowState'],
            'obj_table' => $this['_objectType'],
            'obj_idcolumn' => $idColumn,
            'obj_id' => $this[$idColumn],
            'schemaname' => $schemaName);
        
        // load the real workflow only when required (e. g. when func is edit or delete)
        if (!in_array($currentFunc, array('main', 'view', 'display')) && empty($isReuse)) {
            $result = Zikula_Workflow_Util::getWorkflowForObject($this, $this['_objectType'], $idColumn, 'SimpleMedia');
            if (!$result) {
                $dom = ZLanguage::getModuleDomain('SimpleMedia');
                LogUtil::registerError(__('Error! Could not load the associated workflow.', $dom));
            }
        }
        
        if (!is_object($this['__WORKFLOW__']) && !isset($this['__WORKFLOW__']['schemaname'])) {
            $workflow = $this['__WORKFLOW__'];
            $workflow['schemaname'] = $schemaName;
            $this['__WORKFLOW__'] = $workflow;
        }
    }
    
    /**
     * Resets workflow data back to initial state.
     * To be used after cloning an entity object.
     */
    public function resetWorkflow()
    {
        $this->setWorkflowState('initial');
        $workflowHelper = new SimpleMedia_Util_Workflow(ServiceUtil::getManager());
        $schemaName = $workflowHelper->getWorkflowName($this['_objectType']);
        $this['__WORKFLOW__'] = array(
            'state' => $this['workflowState'],
            'obj_table' => $this['_objectType'],
            'obj_idcolumn' => 'id',
            'obj_id' => 0,
            'schemaname' => $schemaName);
    }
    
    /**
     * Start validation and raise exception if invalid data is found.
     *
     * @return void.
     *
     * @throws Zikula_Exception Thrown if a validation error occurs
     */
    public function validate()
    {
        if ($this->_bypassValidation === true) {
            return;
        }
    
        $result = $this->initValidator()->validateAll();
        if (is_array($result)) {
            throw new Zikula_Exception($result['message'], $result['code'], $result['debugArray']);
        }
    }
    
    /**
     * Return entity data in JSON format.
     *
     * @return string JSON-encoded data.
     */
    public function toJson()
    {
        return json_encode($this->toArray());
    }
    
    /**
     * Collect available actions for this entity.
     */
    protected function prepareItemActions()
    {
        if (!empty($this->_actions)) {
            return;
        }
    
        $currentType = FormUtil::getPassedValue('type', 'user', 'GETPOST', FILTER_SANITIZE_STRING);
        $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
        $dom = ZLanguage::getModuleDomain('SimpleMedia');
        if ($currentType == 'admin') {
            if (in_array($currentFunc, array('main', 'view'))) {
                $this->_actions[] = array(
                    'url' => array('type' => 'user', 'func' => 'display', 'arguments' => array('ot' => 'medium', 'id' => $this['id'], 'slug' => $this->slug)),
                    'icon' => 'preview',
                    'linkTitle' => __('Open preview page', $dom),
                    'linkText' => __('Preview', $dom)
                );
                $this->_actions[] = array(
                    'url' => array('type' => 'admin', 'func' => 'display', 'arguments' => array('ot' => 'medium', 'id' => $this['id'], 'slug' => $this->slug)),
                    'icon' => 'display',
                    'linkTitle' => str_replace('"', '', $this->getTitleFromDisplayPattern()),
                    'linkText' => __('Details', $dom)
                );
            }
            if (in_array($currentFunc, array('main', 'view', 'display'))) {
                $component = 'SimpleMedia:Medium:';
                $instance = $this->id . '::';
                if (SecurityUtil::checkPermission($component, $instance, ACCESS_EDIT)) {
                    $this->_actions[] = array(
                        'url' => array('type' => 'admin', 'func' => 'edit', 'arguments' => array('ot' => 'medium', 'id' => $this['id'])),
                        'icon' => 'edit',
                        'linkTitle' => __('Edit', $dom),
                        'linkText' => __('Edit', $dom)
                    );
                    $this->_actions[] = array(
                        'url' => array('type' => 'admin', 'func' => 'edit', 'arguments' => array('ot' => 'medium', 'astemplate' => $this['id'])),
                        'icon' => 'saveas',
                        'linkTitle' => __('Reuse for new item', $dom),
                        'linkText' => __('Reuse', $dom)
                    );
                }
            }
            if ($currentFunc == 'display') {
                $this->_actions[] = array(
                    'url' => array('type' => 'admin', 'func' => 'view', 'arguments' => array('ot' => 'medium')),
                    'icon' => 'back',
                    'linkTitle' => __('Back to overview', $dom),
                    'linkText' => __('Back to overview', $dom)
                );
            }
        }
        if ($currentType == 'user') {
            if (in_array($currentFunc, array('main', 'view'))) {
                $this->_actions[] = array(
                    'url' => array('type' => 'user', 'func' => 'display', 'arguments' => array('ot' => 'medium', 'id' => $this['id'], 'slug' => $this->slug)),
                    'icon' => 'display',
                    'linkTitle' => str_replace('"', '', $this->getTitleFromDisplayPattern()),
                    'linkText' => __('Details', $dom)
                );
            }
            if (in_array($currentFunc, array('main', 'view', 'display'))) {
            }
            if ($currentFunc == 'display') {
                $this->_actions[] = array(
                    'url' => array('type' => 'user', 'func' => 'view', 'arguments' => array('ot' => 'medium')),
                    'icon' => 'back',
                    'linkTitle' => __('Back to overview', $dom),
                    'linkText' => __('Back to overview', $dom)
                );
            }
        }
    }
    
    /**
     * Creates url arguments array for easy creation of display urls.
     *
     * @return Array The resulting arguments list. 
     */
    public function createUrlArgs()
    {
        $args = array('ot' => $this['_objectType']);
    
        $args['id'] = $this['id'];
    
        if (isset($this['slug'])) {
            $args['slug'] = $this['slug'];
        }
    
        return $args;
    }
    
    /**
     * Create concatenated identifier string (for composite keys).
     *
     * @return String concatenated identifiers.
     */
    public function createCompositeIdentifier()
    {
        $itemId = $this['id'];
    
        return $itemId;
    }
    
    /**
     * Return lower case name of multiple items needed for hook areas.
     *
     * @return string
     */
    public function getHookAreaPrefix()
    {
        return 'simplemedia.ui_hooks.media';
    }

    
    /**
     * Post-Process the data after the entity has been constructed by the entity manager.
     * The event happens after the entity has been loaded from database or after a refresh call.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - no access to associations (not initialised yet)
     *
     * @see SimpleMedia_Entity_Medium::postLoadCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostLoadCallback()
    {
        // echo 'loaded a record ...';
        $currentFunc = FormUtil::getPassedValue('func', 'main', 'GETPOST', FILTER_SANITIZE_STRING);
        $usesCsvOutput = FormUtil::getPassedValue('usecsvext', false, 'GETPOST', FILTER_SANITIZE_STRING);
        
        // initialise the upload handler
        $uploadManager = new SimpleMedia_UploadHandler();
        $serviceManager = ServiceUtil::getManager();
        $controllerHelper = new SimpleMedia_Util_Controller($serviceManager);
        
        $this['id'] = (int) ((isset($this['id']) && !empty($this['id'])) ? DataUtil::formatForDisplay($this['id']) : 0);
        $this->formatTextualField('workflowState', $currentFunc, $usesCsvOutput, true);
        $this->formatTextualField('title', $currentFunc, $usesCsvOutput);
        if (!empty($this['theFile'])) {
            try {
                $basePath = $controllerHelper->getFileBaseFolder('medium', 'theFile');
            } catch (\Exception $e) {
                return LogUtil::registerError($e->getMessage());
            }
        
            $fullPath = $basePath .  $this['theFile'];
            $this['theFileFullPath'] = $fullPath;
            $this['theFileFullPathURL'] = System::getBaseUrl() . $fullPath;
        
            // just some backwards compatibility stuff
            /*if (!isset($this['theFileMeta']) || !is_array($this['theFileMeta']) || !count($this['theFileMeta'])) {
                // assign new meta data
                $this['theFileMeta'] = $uploadManager->readMetaDataForFile($this['theFile'], $fullPath);
            }*/
        }
        $this->formatTextualField('description', $currentFunc, $usesCsvOutput);
        $this->formatTextualField('zipcode', $currentFunc, $usesCsvOutput);
        $this['previewImage'] = (int) ((isset($this['previewImage']) && !empty($this['previewImage'])) ? DataUtil::formatForDisplay($this['previewImage']) : 0);
        $this['sortValue'] = (int) ((isset($this['sortValue']) && !empty($this['sortValue'])) ? DataUtil::formatForDisplay($this['sortValue']) : 0);
        $this->formatTextualField('mediaType', $currentFunc, $usesCsvOutput, true);
        $this['viewsCount'] = (int) ((isset($this['viewsCount']) && !empty($this['viewsCount'])) ? DataUtil::formatForDisplay($this['viewsCount']) : 0);
    
        $this->prepareItemActions();
    
        return true;
    }
    
    /**
     * Formats a given textual field depending on it's actual kind of content.
     *
     * @param string  $fieldName     Name of field to be formatted.
     * @param string  $currentFunc   Name of current controller action.
     * @param string  $usesCsvOutput Whether the output is CSV or not (defaults to false).
     * @param boolean $allowZero     Whether 0 values are allowed or not (defaults to false).
     */
    protected function formatTextualField($fieldName, $currentFunc, $usesCsvOutput = false, $allowZero = false)
    {
        if ($currentFunc == 'edit') {
            // apply no changes when editing the content
            return;
        }
    
        $string = '';
        if (isset($this[$fieldName])) {
            if (!empty($this[$fieldName]) || ($allowZero && $this[$fieldName] == 0)) {
                $string = $this[$fieldName];
                if ($usesCsvOutput == 1) {
                    // strip only quotes when displaying raw output in CSV
                    $string = str_replace('"', '""', $string);
                } else {
                    if ($this->containsHtml($string)) {
                        $string = DataUtil::formatForDisplayHTML($string);
                    } else {
                        $string = DataUtil::formatForDisplay($string);
                        $string = nl2br($string);
                    }
                }
            }
        }
    
        $this[$fieldName] = $string;
    }
    
    /**
     * Checks whether any html tags are contained in the given string.
     * See http://stackoverflow.com/questions/10778035/how-to-check-if-string-contents-have-any-html-in-it for implementation details.
     *
     * @param $string string The given input string.
     *
     * @return boolean Whether any html tags are found or not.
     */
    protected function containsHtml($string)
    {
        return preg_match("/<[^<]+>/", $string, $m) != 0;
    }
    
    /**
     * Pre-Process the data prior to an insert operation.
     * The event happens before the entity managers persist operation is executed for this entity.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - no identifiers available if using an identity generator like sequences
     *     - Doctrine won't recognize changes on relations which are done here
     *       if this method is called by cascade persist
     *     - no creation of other entities allowed
     *
     * @see SimpleMedia_Entity_Medium::prePersistCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPrePersistCallback()
    {
        // echo 'inserting a record ...';
        $this->validate();
    
        return true;
    }
    
    /**
     * Post-Process the data after an insert operation.
     * The event happens after the entity has been made persistant.
     * Will be called after the database insert operations.
     * The generated primary key values are available.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *
     * @see SimpleMedia_Entity_Medium::postPersistCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostPersistCallback()
    {
        // echo 'inserted a record ...';
        return true;
    }
    
    /**
     * Pre-Process the data prior a delete operation.
     * The event happens before the entity managers remove operation is executed for this entity.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - will not be called for a DQL DELETE statement
     *
     * @see SimpleMedia_Entity_Medium::preRemoveCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPreRemoveCallback()
    {
        // delete workflow for this entity
        $workflow = $this['__WORKFLOW__'];
        if ($workflow['id'] > 0) {
            $result = (bool) DBUtil::deleteObjectByID('workflows', $workflow['id']);
            if ($result === false) {
                $dom = ZLanguage::getModuleDomain('SimpleMedia');
                return LogUtil::registerError(__('Error! Could not remove stored workflow. Deletion has been aborted.', $dom));
            }
        }
    
        return true;
    }
    
    /**
     * Post-Process the data after a delete.
     * The event happens after the entity has been deleted.
     * Will be called after the database delete operations.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - will not be called for a DQL DELETE statement
     *
     * @see SimpleMedia_Entity_Medium::postRemoveCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostRemoveCallback()
    {
        // echo 'deleted a record ...';
        $objectId = $this['id'];
        // initialise the upload handler
        $uploadManager = new SimpleMedia_UploadHandler();
    
        $uploadFields = array('theFile');
        foreach ($uploadFields as $uploadField) {
            if (empty($this->$uploadField)) {
                continue;
            }
    
            // remove upload file (and image thumbnails)
            $uploadManager->deleteUploadFile('medium', $this, $uploadField, $objectId);
        }
    
        return true;
    }
    
    /**
     * Pre-Process the data prior to an update operation.
     * The event happens before the database update operations for the entity data.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - will not be called for a DQL UPDATE statement
     *     - changes on associations are not allowed and won't be recognized by flush
     *     - changes on properties won't be recognized by flush as well
     *     - no creation of other entities allowed
     *
     * @see SimpleMedia_Entity_Medium::preUpdateCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPreUpdateCallback()
    {
        // echo 'updating a record ...';
        $this->validate();
    
        return true;
    }
    
    /**
     * Post-Process the data after an update operation.
     * The event happens after the database update operations for the entity data.
     *
     * Restrictions:
     *     - no access to entity manager or unit of work apis
     *     - will not be called for a DQL UPDATE statement
     *
     * @see SimpleMedia_Entity_Medium::postUpdateCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostUpdateCallback()
    {
        // echo 'updated a record ...';
        return true;
    }
    
    /**
     * Pre-Process the data prior to a save operation.
     * This combines the PrePersist and PreUpdate events.
     * For more information see corresponding callback handlers.
     *
     * @see SimpleMedia_Entity_Medium::preSaveCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPreSaveCallback()
    {
        // echo 'saving a record ...';
        $this->validate();
    
        return true;
    }
    
    /**
     * Post-Process the data after a save operation.
     * This combines the PostPersist and PostUpdate events.
     * For more information see corresponding callback handlers.
     *
     * @see SimpleMedia_Entity_Medium::postSaveCallback()
     * @return boolean true if completed successfully else false.
     */
    protected function performPostSaveCallback()
    {
        // echo 'saved a record ...';
        return true;
    }
    

    /**
     * Returns the formatted title conforming to the display pattern
     * specified for this entity.
     */
    public function getTitleFromDisplayPattern()
    {
        $formattedTitle = $this->getTitle();
    
        return $formattedTitle;
    }

    /**
     * ToString interceptor implementation.
     * This method is useful for debugging purposes.
     */
    public function __toString()
    {
        return $this->getId();
    }

    /**
     * Clone interceptor implementation.
     * This method is for example called by the reuse functionality.
     * Performs a deep copy. 
     *
     * See also:
     * (1) http://docs.doctrine-project.org/en/latest/cookbook/implementing-wakeup-or-clone.html
     * (2) http://www.sunilb.com/php/php5-oops-tutorial-magic-methods-__clone-method
     * (3) http://stackoverflow.com/questions/185934/how-do-i-create-a-copy-of-an-object-in-php
     * (4) http://www.pantovic.com/article/26/doctrine2-entity-cloning
     */
    public function __clone()
    {
        // If the entity has an identity, proceed as normal.
        if ($this->id) {
            // create new instance
            
            $entity = new \SimpleMedia_Entity_Medium();
            // unset identifiers
            $entity->setId(null);
            // copy simple fields
            $entity->set_objectType($this->get_objectType());
            $entity->set_actions($this->get_actions());
            $entity->initValidator();
            $entity->setTitle($this->getTitle());
            $entity->setTheFile($this->getTheFile());
            $entity->setDescription($this->getDescription());
            $entity->setZipcode($this->getZipcode());
            $entity->setPreviewImage($this->getPreviewImage());
            $entity->setSortValue($this->getSortValue());
            $entity->setMediaType($this->getMediaType());
            $entity->setViewsCount($this->getViewsCount());
    
            // handle related objects
            // prevent shared references by doing a deep copy - see (2) and (3) for more information
            if ($this->getCollection() != null) {
                $this->collection = clone $this->collection;
                $entity->setCollection($this->collection);
            }
    
            return $entity;
        }
        // otherwise do nothing, do NOT throw an exception!
    }
}
