<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Sat Oct 27 20:20:23 CEST 2012.
 */

/**
 * Item selector plugin base class.
 */
class SimpleMedia_Form_Plugin_Base_ItemSelector extends Zikula_Form_Plugin_TextInput
{
    protected $objectType = '';
    protected $selectedItemId = 0;

    /**
     * Get filename of this file.
     * The information is used to re-establish the plugins on postback.
     *
     * @return string
     */
    public function getFilename()
    {
        return __FILE__;
    }

    /**
     * Create event handler.
     *
     * @param Zikula_Form_View $view    Reference to Zikula_Form_View object.
     * @param array            &$params Parameters passed from the Smarty plugin function.
     *
     * @see    Zikula_Form_AbstractPlugin
     * @return void
     */
    public function create(Zikula_Form_View $view, &$params)
    {
        $params['maxLength'] = 11;
        /*$params['width'] = '8em';*/

        // let parent plugin do the work in detail
        parent::create($view, $params);
    }

    /**
     * Helper method to determine css class.
     *
     * @see    Zikula_Form_Plugin_TextInput
     *
     * @return string the list of css classes to apply
     */
    protected function getStyleClass()
    {
        $class = parent::getStyleClass();
        return str_replace('z-form-text', 'z-form-itemselector ' . strtolower($this->objectType), $class);
    }

    /**
     * Render event handler.
     *
     * @param Zikula_Form_View $view Reference to Zikula_Form_View object.
     *
     * @return string The rendered output
     */
    public function render(Zikula_Form_View $view)
    {
        static $firstTime = true;
        if ($firstTime) {
            PageUtil::addVar('javascript', 'prototype');
            PageUtil::addVar('javascript', 'Zikula.UI'); // imageviewer
            PageUtil::addVar('javascript', 'modules/SimpleMedia/javascript/finder.js');
            PageUtil::addVar('stylesheet', ThemeUtil::getModuleStylesheet('SimpleMedia'));
        }
        $firstTime = false;

        if (!SecurityUtil::checkPermission('SimpleMedia:' . ucwords($this->objectType) . ':', '::', ACCESS_COMMENT)) {
            return false; //LogUtil::registerPermissionError();
        }

        $categorisableObjectTypes = array('medium', 'collection');
        $mainCategory = null;
        $catId = 0;
        if (in_array($this->objectType, $categorisableObjectTypes)) {
            $mainCategory = ModUtil::apiFunc('SimpleMedia', 'category', 'getMainCat', array('ot' => $this->objectType));
            $catId = (int) FormUtil::getPassedValue('catid', 0, 'POST', FILTER_SANITIZE_INT);
        }

        $serviceManager = ServiceUtil::getManager();
        $entityManager = $serviceManager->getService('doctrine.entitymanager');

        $repository = $entityManager->getRepository('SimpleMedia_Entity_' . ucfirst($this->objectType));

        $sort = $repository->getDefaultSortingField();
        $sdir = 'asc';

        // convenience vars to make code clearer
        $where = '';
        $sortParam = $sort . ' ' . $sdir;

        $objectData = $repository->selectWhere($where, $sortParam);

        $view = Zikula_View::getInstance('SimpleMedia', false);
        $view->assign('items', $objectData)
        ->assign('mainCategory', $mainCategory)
        ->assign('catID', $catId)
             ->assign('selectedId', $this->selectedItemId);

        return $view->fetch('external/' . $this->objectType . '/selectItem.tpl');
    }

    /**
     * Decode event handler.
     *
     * @param Zikula_Form_View $view Zikula_Form_View object.
     *
     * @return void
     */
    public function decode(Zikula_Form_View $view)
    {
        parent::decode($view);
        $value = explode(';', $this->text);
        $this->objectType = $value[0];
        $this->selectedItemId = $value[1];
    }

    /**
     * Parses a value.
     *
     * @param Zikula_Form_View $view Reference to Zikula_Form_View object.
     * @param string           $text Text.
     *
     * @return string Parsed Text.
     */
    public function parseValue(Zikula_Form_View $view, $text)
    {
        $valueParts = array($this->objectType, $this->selectedItemId);
        return implode(';', $valueParts);
    }

    /**
     * Load values.
     *
     * Called internally by the plugin itself to load values from the render.
     * Can also by called when some one is calling the render object's Zikula_Form_ViewetValues.
     *
     * @param Zikula_Form_View $view    Reference to Zikula_Form_View object.
     * @param array            &$values Values to load.
     *
     * @return void
     */
    public function loadValue(Zikula_Form_View $view, &$values)
    {
        if (!$this->dataBased) {
            return;
        }

        $value = null;

        if ($this->group == null) {
            if (array_key_exists($this->dataField, $values)) {
                $value = $values[$this->dataField];
            }
        } else {
            if (array_key_exists($this->group, $values) && array_key_exists($this->dataField, $values[$this->group])) {
                $value = $values[$this->group][$this->dataField];
            }
        }

        if ($value !== null) {
            //$this->text = $this->formatValue($view, $value);
            $value = explode(';', $value);
            $this->objectType = $value[0];
            $this->selectedItemId = $value[1];
        }
    }
}
