<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ZKM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * The simplemediaTreeSelector plugin cares for handling a dropdown list
 * for an entity with tree structure.
 *
 * @param array            $params Parameters passed to this function from the template.
 * @param Zikula_Form_View $view   Reference to Form render object.
 *
 * @return string The rendered output.
 */
function smarty_function_simplemediaTreeSelector($params, $view)
{
    return $view->registerPlugin('SimpleMedia_Form_Plugin_TreeSelector', $params);
}
