<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * The simplemediaFormatGeoData modifier formats geo data.
 *
 * @param string $string The data to be formatted.
 *
 * @return string The formatted output.
 */
function smarty_modifier_simplemediaFormatGeoData($string)
{
    return number_format($string, 7, '.', '');
}
