<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Mon Nov 05 23:27:06 CET 2012.
 */

/**
 * Generic single item display content plugin implementation class.
 */
class SimpleMedia_ContentType_Item extends SimpleMedia_ContentType_Base_Item
{
    // feel free to extend the content type here
}

function SimpleMedia_Api_ContentTypes_item($args)
{
    return new SimpleMedia_Api_ContentTypes_itemPlugin();
}
