<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Sat Oct 27 20:20:23 CEST 2012.
 */

/**
 * Generic item list content plugin implementation class.
 */
class SimpleMedia_ContentType_ItemList extends SimpleMedia_ContentType_Base_ItemList
{
    // feel free to extend the content type here
}

function SimpleMedia_Api_ContentTypes_itemlist($args)
{
    return new SimpleMedia_Api_ContentTypes_itemListPlugin();
}
