<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Sat Oct 27 20:20:23 CEST 2012.
 */

/**
 * Colour field plugin including colour picker.
 *
 * The allowed formats are '#RRGGBB' and '#RGB'.
 *
 * You can also use all of the features from the Zikula_Form_Plugin_TextInput plugin since
 * the colour input inherits from it.
 */
class SimpleMedia_Form_Plugin_ColourInput extends SimpleMedia_Form_Plugin_Base_ColourInput
{
    // feel free to add your customisation here
}
