<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Sat Oct 27 20:20:23 CEST 2012.
 */

/**
 * Tree selector.
 *
 * This plugin creates a nested tree selector using a dropdown list.
 * The selected value of the base dropdown list will be set to ID of the selected tree node.
 */
class SimpleMedia_Form_Plugin_TreeSelector extends SimpleMedia_Form_Plugin_Base_TreeSelector
{
    // feel free to add your customisation here
}
