<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ZKM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This class provides object meta data for the Tag module.
 */
class SimpleMedia_TaggedObjectMeta_SimpleMedia extends SimpleMedia_TaggedObjectMeta_Base_SimpleMedia
{
    // feel free to extend the tag support here
}
