<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Installer implementation class.
 */
class SimpleMedia_Installer extends SimpleMedia_Base_Installer
{
    /**
     * Install the SimpleMedia application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        $result = parent::install();
        if (!$result) {
            return $result;
        }

        $this->setVar('mediaPageSize', 15);
        $this->setVar('collectionsPageSize', 6);
        $this->setVar('mediumFullImaginePreset', ''); // by default empty, use original image
        $this->setVar('shrinkDimensions', array('width' => 1600, 'height' => 1200));

        $categoryRegistryIdsPerEntity = array();

        // create the default categories
        $this->createDefaultCategories($categoryRegistryIdsPerEntity);
        LogUtil::registerStatus($this->__('A Category tree for SimpleMedia has been created at [Root/Modules/SimpleMedia].'));

		// create Imagine presets for collections and media and set variables
        /** @var SystemPlugin_Imagine_Plugin $imaginePlugin */
        $imaginePlugin = $this->getServiceManager()->getService('systemplugin.imagine.manager')->getPlugin();
		if (!$imaginePlugin->hasPreset('simplemedia_medium')) {
			$imaginePlugin->setPreset(new SystemPlugin_Imagine_Preset('simplemedia_medium', array(
                    'width' => 200,
                    'height' => 200,
					'mode' => 'outbound',
					'__module' => 'SimpleMedia'
                )));
		}
		$this->setVar('mediumImaginePreset', 'simplemedia_medium');
		if (!$imaginePlugin->hasPreset('simplemedia_medium_full')) {
			$imaginePlugin->setPreset(new SystemPlugin_Imagine_Preset('simplemedia_medium_full', array(
                    'width' => 1600,
                    'height' => 1600,
					'mode' => 'inset',
					'__module' => 'SimpleMedia'
                )));
		}
		// $this->setVar('collectionImaginePreset', 'simplemedia_medium_full');
		if (!$imaginePlugin->hasPreset('simplemedia_collection')) {
			$imaginePlugin->setPreset(new SystemPlugin_Imagine_Preset('simplemedia_collection', array(
                    'width' => 200,
                    'height' => 200,
					'mode' => 'outbound',
					'__module' => 'SimpleMedia'
                )));
		}
		$this->setVar('collectionImaginePreset', 'simplemedia_collection');
		
        // initialisation successful
        return true;
    }

    /**
     * Create the default data for SimpleMedia.
     *
     * @param array $categoryRegistryIdsPerEntity
     *
     * @return void
     */
    protected function createDefaultData($categoryRegistryIdsPerEntity)
    {
        // call the parent class
        parent::createDefaultData($categoryRegistryIdsPerEntity);

        // add a default root collection
        try {
            $collection = new SimpleMedia_Entity_Collection();
            $collection->setTitle($this->__('Default collection'));
            $collection->setDescription($this->__('This is the default root collection for your media and collections'));
			// make collection approved from start
			$collection->setWorkflowState('approved');
			// categories not set (yet)

            $this->entityManager->persist($collection);
            $this->entityManager->flush();
			// set this as default collection id for new media
			$this->setVar('defaultCollection', $collection->getId());
        } catch (Exception $e) {
            return LogUtil::registerError($e->getMessage());
        }
    }

    /**
     * Create the default data for SimpleMedia. NEW
     *
     * @param $categoryRegistryIdsPerEntity
     *
     * @throws Zikula_Exception
     * @return void
     */
    protected function createDefaultCategories(&$categoryRegistryIdsPerEntity)
    {
        // add default entry for category registry (property named Main)
        include_once 'modules/SimpleMedia/lib/SimpleMedia/Api/Base/Category.php';
        include_once 'modules/SimpleMedia/lib/SimpleMedia/Api/Category.php';
        $categoryApi = new SimpleMedia_Api_Category($this->serviceManager);

        // create Collection category root
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules', 'SimpleMedia', null, $this->__('SimpleMedia'), $this->__('SimpleMedia collections and media categories'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia'));
            }
        }
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Collection')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules/SimpleMedia', 'Collection', null, $this->__('Collection'), $this->__('SimpleMedia collections'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia/Collection'));
            }
        }
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Collection/Default')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules/SimpleMedia/Collection', 'Default', null, $this->__('Default'), $this->__('Default collection category'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia/Collection/Default'));
            }
        }
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Medium')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules/SimpleMedia', 'Medium', null, $this->__('Medium'), $this->__('SimpleMedia media'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia/Medium'));
            }
        }
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Medium/Image')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules/SimpleMedia/Medium', 'Image', null, $this->__('Image'), $this->__('SimpleMedia media Image'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia/Medium/Image'));
            }
        }
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Medium/Movie')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules/SimpleMedia/Medium', 'Movie', null, $this->__('Movie'), $this->__('SimpleMedia media Movie'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia/Medium/Movie'));
            }
        }
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Medium/Audio')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules/SimpleMedia/Medium', 'Audio', null, $this->__('Audio'), $this->__('SimpleMedia media Audio'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia/Medium/Audio'));
            }
        }
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Medium/Documents')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules/SimpleMedia/Medium', 'Documents', null, $this->__('Documents'), $this->__('SimpleMedia media Documents'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia/Medium/Documents'));
            }
        }
        if (!CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Medium/Other')) {
            if (!CategoryUtil::createCategory('/__SYSTEM__/Modules/SimpleMedia/Medium', 'Other', null, $this->__('Other'), $this->__('SimpleMedia media Other'))) {
                throw new Zikula_Exception($this->__f('Cannot create %s Category.', 'Modules/SimpleMedia/Medium/Other'));
            }
        }
        $catCollection = CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Collection');
        $catMedium = CategoryUtil::getCategoryByPath('/__SYSTEM__/Modules/SimpleMedia/Medium');

        $registryData = array();
        $registryData['modname'] = $this->name;
        $registryData['table'] = 'Medium';
        $registryData['property'] = $categoryApi->getPrimaryProperty(array('ot' => 'Medium'));
        $registryData['category_id'] = $catMedium['id'];
        $registryData['id'] = false;
        if (!DBUtil::insertObject($registryData, 'categories_registry')) {
            LogUtil::registerError($this->__f('Error! Could not create a category registry for the %s entity.', array('medium')));
        }
        $categoryRegistryIdsPerEntity['medium'] = $registryData['id'];

        $registryData = array();
        $registryData['modname'] = $this->name;
        $registryData['table'] = 'Collection';
        $registryData['property'] = $categoryApi->getPrimaryProperty(array('ot' => 'Collection'));
        $registryData['category_id'] = $catCollection['id'];
        $registryData['id'] = false;
        if (!DBUtil::insertObject($registryData, 'categories_registry')) {
            LogUtil::registerError($this->__f('Error! Could not create a category registry for the %s entity.', array('collection')));
        }
        $categoryRegistryIdsPerEntity['collection'] = $registryData['id'];
    }

    /**
     * register persistent module handlers 
	 * OVERRIDE: added scribite external plugins for tinymce, ckeditor
     * 
     * @return void
     */
    public function registerPersistentEventHandlers()
    {
        parent::registerPersistentEventHandlers();
        
        EventUtil::registerPersistentModuleHandler('SimpleMedia', 'module.scribite.editorhelpers', array('SimpleMedia_Listener_ThirdParty', 'getEditorHelpers'));
        EventUtil::registerPersistentModuleHandler('SimpleMedia', 'moduleplugin.tinymce.externalplugins', array('SimpleMedia_Listener_ThirdParty', 'getTinyMcePlugins'));
        EventUtil::registerPersistentModuleHandler('SimpleMedia', 'moduleplugin.ckeditor.externalplugins', array('SimpleMedia_Listener_ThirdParty', 'getCKEditorPlugins'));
    }
    
    /**
     * Uninstall SimpleMedia. 
	 * OVERRIDE: added extra message on category tree removal
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        $result = parent::uninstall();
        
        LogUtil::registerStatus($this->__('The SimpleMedia category [Root/Modules/SimpleMedia] with subcategories can be removed manually'));
        
        return $result;
    }
}
