<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ZKM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Upload handler implementation class.
 */
class SimpleMedia_UploadHandler extends SimpleMedia_Base_UploadHandler
{
    // feel free to add your upload handler enhancements here

    /**
     * @var array List of file types to be considered as movies.
     */
    protected $movieFileTypes;

    /**
     * @var array List of file types to be considered as audio.
     */
    protected $audioFileTypes;

    /**
     * @var array List of file types to be considered as documents.
     */
    protected $documentFileTypes;

    /**
     * Constructor initialising the supported object types.
     */
    public function __construct()
    {
        parent::__construct();
        
        // see for instance http://en.wikipedia.org/wiki/List_of_file_formats
        $this->imageFileTypes = array('gif', 'jpeg', 'jpg', 'png', 'tif', 'tiff', 'bmp'); // raster images
        $this->audioFileTypes = array('aac', 'mp3', 'wav', 'aif', 'mid');
        $this->movieFileTypes = array('mpg', 'mpeg', 'mp4', 'mov', 'wmv', 'avi', 'swf', 'flv', 'rm', 'f4v', 'h264');

        $otherimageFileTypes = array('psd', 'eps', 'ps', 'ai', 'svg', 'odg', 'emf', 'dwg', 'dxf');
        $ebookFileTypes = array('epub', 'mobi');
        $camerarawFileTypes = array('dng', 'cr2', 'nef');
        $geoFileTypes = array('kml', 'gpx');
        $dtpFileTypes = array('qxd', 'fm', 'indd');
        $this->documentFileTypes = array_merge(
            array('pdf', 'doc', 'xls', 'ppt', 'docx', 'xlsx', 'pptx', 'odt', 'ods', 'odp', 'pages', 'numbers', 'key', 'keynote', 'txt', 'rtf', 'csv', 'tex'), 
            $otherimageFileTypes, $ebookFileTypes, $camerarawFileTypes, $geoFileTypes, $dtpFileTypes
        );
        
        // zip and other package files will go into other
    }


    /**
     * Determines the allowed file extensions for a given object type.
     * OVERRIDE: using allowedExtensions
     *
     * @param string $objectType Currently treated entity type.
     * @param string $fieldName  Name of upload field.
     * @param string $extension  Input file extension.
     *
     * @return array the list of allowed file extensions
     */
    protected function isAllowedFileExtension($objectType, $fieldName, $extension)
    {
        // determine the allowed extensions
        $allowedExtensions = array();
        switch ($objectType) {
            case 'medium':
                //$allowedExtensions = array('gif', 'jpeg', 'jpg', 'png', 'pdf', 'doc', 'xls', 'ppt', 'docx', 'xlsx', 'pptx', 'odt', 'ods', 'odp', 'arj', 'zip', 'rar', 'tar', 'tgz', 'gz', 'bz2', 'txt', 'rtf', 'swf', 'flv', 'mp3', 'mp4', 'avi', 'mpg', 'mpeg', 'mov');
                $allowedExtensions = explode(',', str_replace(' ', '', ModUtil::getVar('SimpleMedia', 'allowedExtensions')));
                    break;
        }
    
        if (count($allowedExtensions) > 0) {
            if (!in_array($extension, $allowedExtensions)) {
                return false;
            }
        }
    
        if (in_array($extension, $this->forbiddenFileTypes)) {
            return false;
        }
    
        return true;
    }
    
    /**
     * Read meta data from a certain file. 
     * OVERRIDE adding exif/iptc vars
     *
     * @param string $fileName  Name of file to be processed.
     * @param string $filePath  Path to file to be processed.
     *
     * @return array collected meta data
     */
    public function readMetaDataForFile($fileName, $filePath)
    {
        // call parent class
        $meta = parent::readMetaDataForFile($fileName, $filePath);

//        $iptc = new SimpleMedia_Util_Iptc($filePath);
//        print_r($iptc->fetchAll(SimpleMedia_Util_Iptc::KEYWORDS));
//        print_r($iptc->dump());
        
/*
1	IMAGETYPE_GIF
2	IMAGETYPE_JPEG
3	IMAGETYPE_PNG
4	IMAGETYPE_SWF
5	IMAGETYPE_PSD
6	IMAGETYPE_BMP
7	IMAGETYPE_TIFF_II (intel byte order)
8	IMAGETYPE_TIFF_MM (motorola byte order)
9	IMAGETYPE_JPC
10	IMAGETYPE_JP2
11	IMAGETYPE_JPX
12	IMAGETYPE_JB2
13	IMAGETYPE_SWC
14	IMAGETYPE_IFF
15	IMAGETYPE_WBMP
16	IMAGETYPE_XBM
17	IMAGETYPE_ICO
*/            
/*        $imagetype = exif_imagetype($filePath);
        echo $imagetype . "\n<br>";
        if ($imagetype == 2) {

            // EXIF
            $exif = exif_read_data($filePath, 0, true);
            if ($exif) {
                foreach ($exif as $key => $section) {
                    foreach ($section as $name => $val) {
                        echo "$key.$name: $val\n<br>";
                    }
                }
            }

            // IPTC
            $size = getimagesize($filePath, $info);
            if(is_array($info)) {
                $iptc = iptcparse($info["APP13"]);
                foreach (array_keys($iptc) as $s) {
                    $c = count ($iptc[$s]);
                    for ($i=0; $i <$c; $i++)
                    {
                        echo $s.' = '.$iptc[$s][$i].'<br>';
                    }
                }
            }

        }
*/

/*        
        $extensionarr = explode('.', $fileName);
        $meta = array();
        $meta['extension'] = strtolower($extensionarr[count($extensionarr) - 1]);
        $meta['size'] = filesize($filePath);
        $meta['isImage'] = (in_array($meta['extension'], $this->imageFileTypes) ? true : false);
    
        if (!$meta['isImage']) {
            return $meta;
        }
    
        if ($meta['extension'] == 'swf') {
            $meta['isImage'] = false;
        }
    
        $imgInfo = getimagesize($filePath);
        if (!is_array($imgInfo)) {
            return $meta;
        }
    
        $meta['width'] = $imgInfo[0];
        $meta['height'] = $imgInfo[1];
    
        if ($imgInfo[1] < $imgInfo[0]) {
            $meta['format'] = 'landscape';
        } elseif ($imgInfo[1] > $imgInfo[0]) {
            $meta['format'] = 'portrait';
        } else {
            $meta['format'] = 'square';
        }
    
*/
        return $meta;

    }    
}
