<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing medium categories.
 *
 * This is the concrete category class for medium entities.
* @ORM\Entity(repositoryClass="SimpleMedia_Entity_Repository_MediumCategory")
   * @ORM\Table(name="simmed_medium_category",
   *     uniqueConstraints={
   *         @ORM\UniqueConstraint(name="cat_unq", columns={"registryId", "categoryId", "entityId"})
   *     }
   * )
 */
class SimpleMedia_Entity_MediumCategory extends SimpleMedia_Entity_Base_MediumCategory
{
    // feel free to add your own methods here
}
