<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

use Doctrine\ORM\Mapping as ORM;

/**
 * Entity extension domain class storing medium meta data.
 *
 * This is the concrete meta data class for medium entities.
* @ORM\Entity(repositoryClass="SimpleMedia_Entity_Repository_MediumMetaData")
   * @ORM\Table(name="simmed_medium_metadata")
 */
class SimpleMedia_Entity_MediumMetaData extends SimpleMedia_Entity_Base_MediumMetaData
{
    // feel free to add your own methods here

    /**
     * @ORM\Column(type="string", length=80, nullable=true)
     * @var string
     */
    private $rights;

    public function getRights()
    {
        return $this->rights;
    }

    public function setRights($rights)
    {
        $this->rights = $rights;
    }

}
