<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Sat Oct 27 20:20:23 CEST 2012.
 */

/**
 * The simplemediaTreeSelector plugin cares for handling a dropdown list
 * for an entity with tree structure.
 *
 * @param array            $params Parameters passed to this function from the template.
 * @param Zikula_Form_View $view   Reference to Form render object.
 *
 * @return string The rendered output.
 */
function smarty_function_simplemediaTreeSelector($params, $view)
{
    return $view->registerPlugin('SimpleMedia_Form_Plugin_TreeSelector', $params);
}
