<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Sat Oct 27 20:20:23 CEST 2012.
 */

/**
 * The simplemediaTreeJS plugin delivers the html output for a JS tree
 * based on given tree entities.
 *
 * Available parameters:
 *   - objectType: Name of treated object type.
 *   - tree:       Object collection with tree items.
 *   - controller: Optional name of controller, defaults to 'user'.
 *   - root:       Optional id of root node, defaults to 1.
 *   - assign:     If set, the results are assigned to the corresponding variable instead of printed out.
 *
 * @param  array       $params  All attributes passed to this function from the template.
 * @param  Zikula_View $view    Reference to the view object.
 *
 * @return string The output of the plugin.
 */
function smarty_function_simplemediaTreeJS($params, $view)
{
    if (!isset($params['objectType']) || empty($params['objectType'])) {
        $view->trigger_error(__f('Error! in %1$s: the %2$s parameter must be specified.', array('simplemediaTreeJS', 'objectType')));
        return false;
    }

    if (!isset($params['tree']) || empty($params['tree'])) {
        $view->trigger_error(__f('Error! in %1$s: the %2$s parameter must be specified.', array('simplemediaTreeJS', 'tree')));
        return false;
    }

    if (!isset($params['controller']) || empty($params['controller'])) {
        $params['controller'] = 'user';
    }

    if (!isset($params['root']) || empty($params['root'])) {
        $params['root'] = 1;
    }

    // check whether an edit action is available
    $controllerHasEditAction = false;
    switch ($params['controller']) {
        case 'admin': $controllerHasEditAction = true; break;
    }

    $serviceManager = ServiceUtil::getManager();
    $entityManager = $serviceManager->getService('doctrine.entitymanager');
    $repository = $entityManager->getRepository('SimpleMedia_Entity_' . ucfirst($params['objectType']));
    $titleFieldName = $repository->getTitleFieldName();
    $descriptionFieldName = $repository->getDescriptionFieldName();


    $idField = 'id';
    $result = array();

    foreach ($params['tree'] as $item) {
        $url = (($controllerHasEditAction) ? ModUtil::url('SimpleMedia', $params['controller'], 'edit', array('ot' => $params['objectType'], $idField => $item[$idField])) : '');

        $parentItem = $item->getParent();

        $result[] = array('id' => $item[$idField],
                          'parent_id' => $parentItem[$idField],
                          'name' => (($titleFieldName != '') ? $item[$titleFieldName] : ''),
                          'title' => (($descriptionFieldName != '') ? strip_tags($item[$descriptionFieldName]) : ''),
                        //'icon' => '',
                        //'class' => '',
                          'active' => true,
                        //'expanded' => null,
                          'href' => $url);
    }

    // instantiate and initialise the output tree object
    $tree = new Zikula_Tree();
    $tree->setOption('id', 'itemtree' . $params['root']);
    //$tree->setOption('objid', $idField);
    $tree->setOption('treeClass', 'z-nestedsetlist');
    $tree->setOption('nodePrefix', 'tree' . $params['root'] . 'node_');
    $tree->setOption('sortable', ((isset($params['sortable']) && $params['sortable']) ? true : false));
    $tree->setOption('withWraper', true);

    // disable drag and drop for root category
    $tree->setOption('disabled', array(1));

    // put data into output tree
    $tree->loadArrayData($result);

    // get output result
    $result = $tree->getHTML();

    if (array_key_exists('assign', $params)) {
        $view->assign($params['assign'], $result);
        return;
    }
    return $result;
}
