<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Sat Oct 27 20:20:23 CEST 2012.
 */

/**
 * The simplemediaGetListEntry modifier displays the name
 * or names for a given list item.
 *
 * @param string  $value      The dropdown value to process.
 * @param string  $objectType The treated object type.
 * @param string  $fieldName  The list field's name.
 * @param string  $delimiter  String used as separator for multiple selections.
 *
 * @return string List item name.
 */
function smarty_modifier_simplemediaGetListEntry($value, $objectType = '', $fieldName = '', $delimiter = ', ')
{
    if (empty($value) || empty($objectType) || empty($fieldName)) {
        return $value;
    }

    $serviceManager = ServiceUtil::getManager();
    $helper = new SimpleMedia_Util_ListEntries($serviceManager);
    return $helper->resolve($value, $objectType, $fieldName, $delimiter);
}
