# Examples:
#system/System/templates/example.tpl: config/templates/System/example.tpl
#modules/System/templates/example.tpl: config/modules/System/example.tpl

modules/SimpleMedia/templates/admin/config.tpl: config/templates/SimpleMedia/admin/config.tpl
modules/SimpleMedia/templates/admin/include_metadata_display.tpl: config/templates/SimpleMedia/admin/include_metadata_display.tpl
modules/SimpleMedia/templates/admin/include_metadata_edit.tpl: config/templates/SimpleMedia/admin/include_metadata_edit.tpl

modules/SimpleMedia/templates/admin/collection/view.tpl: config/templates/SimpleMedia/admin/collection/view.tpl
modules/SimpleMedia/templates/admin/medium/edit.tpl: config/templates/SimpleMedia/admin/medium/edit.tpl
modules/SimpleMedia/templates/admin/medium/display.tpl: config/templates/SimpleMedia/admin/medium/display.tpl

modules/SimpleMedia/templates/user/header.tpl: config/templates/SimpleMedia/user/header.tpl
modules/SimpleMedia/templates/user/include_standardfields_display.tpl: /config/templates/SimpleMedia/user/include_standardfields_display.tpl
modules/SimpleMedia/templates/user/include_metadata_display.tpl: /config/templates/SimpleMedia/user/include_metadata_display.tpl
modules/SimpleMedia/templates/user/multiUpload.tpl: config/templates/SimpleMedia/user/multiUpload.tpl

modules/SimpleMedia/templates/user/collection/view.tpl: config/templates/SimpleMedia/user/collection/view.tpl
modules/SimpleMedia/templates/user/collection/edit.tpl: config/templates/SimpleMedia/user/collection/edit.tpl
modules/SimpleMedia/templates/user/collection/display.tpl: config/templates/SimpleMedia/user/collection/display.tpl
modules/SimpleMedia/templates/user/collection/view_items.tpl: config/templates/SimpleMedia/user/collection/view_items.tpl
modules/SimpleMedia/templates/user/medium/include_displayItemListMany.tpl: /config/templates/SimpleMedia/user/medium/include_displayItemListMany.tpl
modules/SimpleMedia/templates/user/medium/display.tpl: /config/templates/SimpleMedia/user/medium/display.tpl
