# Examples:
#system/System/templates/example.tpl: config/templates/System/example.tpl
#modules/System/templates/example.tpl: config/modules/System/example.tpl

#modules/SimpleMedia/templates/admin/config.tpl: config/templates/SimpleMedia/admin/config.tpl
#modules/SimpleMedia/templates/admin/main.tpl:  config/templates/SimpleMedia/admin/main.tpl

