<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * This is the User api helper class.
 */
class SimpleMedia_Api_User extends SimpleMedia_Api_Base_User
{
    // feel free to add own api methods here

    /**
     * Returns available user panel links.
	 * OVERRIDE:
     * CHECK
	 * - removed direct media viewing, always via collections
	 * - Removed tree from the collection template, since that is not usefull in the frontend.
     *
     * @return array Array of user links.
     */
    public function getlinks()
    {
        $links = array();
		
		// get the current url parameters
		$ot = $this->request->getGet()->filter('ot', 'collection', FILTER_SANITIZE_STRING);
		$id = $this->request->getGet()->filter('id' , 0 , FILTER_SANITIZE_NUMBER_INT);

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'main'),
                             'text' => $this->__('Backend'),
                             'title' => $this->__('Switch to administration area.'),
                             'class' => 'z-icon-es-options');
        }

        $controllerHelper = new SimpleMedia_Util_Controller($this->serviceManager);
        $utilArgs = array('api' => 'user', 'action' => 'getlinks');
        $allowedObjectTypes = $controllerHelper->getObjectTypes('api', $utilArgs);

        if (in_array('collection', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Collection:', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'view', array('ot' => 'collection')),
                             'text' => $this->__('Collections'),
                             'title' => $this->__('Collection list'));
        }
        /*
        if (in_array('medium', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Medium:', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'view', array('ot' => 'medium')),
                             'text' => $this->__('Media'),
                             'title' => $this->__('Medium list'));
        }
        */
		// Add single media only when in a collection
        if (in_array('medium', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Medium:', '::', ACCESS_ADD) && $id > 0) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'edit', array('ot' => 'medium', 'collection' => $id)),
                'text' => $this->__('Add medium'),
                'title' => $this->__('Upload a medium'));
        }
        if (in_array('medium', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Medium:', '::', ACCESS_ADD)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'multiUpload', array('collection' => $id)),
                'text' => $this->__('MultiUpload media'),
                'title' => $this->__('Upload several media at once'));
        }
        if (in_array('collection', $allowedObjectTypes)
            && SecurityUtil::checkPermission($this->name . ':Collection:', '::', ACCESS_ADD)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'addCollection', array('ot' => 'collection', 'pid' => $id)),
                'text' => $this->__('Add Collection'),
                'title' => $this->__('Add a root collection'));
        }

        return $links;
    }
}
