<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * This handler class handles the page events of the Form called by the simpleMedia_medium_edit() function.
 * It aims on the medium object type.
 */
class SimpleMedia_Form_Handler_Medium_Edit extends SimpleMedia_Form_Handler_Medium_Base_Edit
{
    // feel free to extend the base handler class here
}
