<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Mon Nov 05 23:27:05 CET 2012.
 */

/**
 * This is the User api helper class.
 */
class SimpleMedia_Api_User extends SimpleMedia_Api_Base_User
{
    // feel free to add own api methods here

    /**
     * Returns available user panel links. OVERRIDE
     *
     * @return array Array of user links.
     */
    public function getlinks()
    {
        $links = array();

        if (SecurityUtil::checkPermission($this->name . '::', '::', ACCESS_ADMIN)) {
            $links[] = array('url' => ModUtil::url($this->name, 'admin', 'main'),
                             'text' => $this->__('Backend'),
                             'title' => $this->__('Switch to administration area.'),
                             'class' => 'z-icon-es-options');
        }
        if (SecurityUtil::checkPermission($this->name . ':Collection:', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'view', array('ot' => 'collection')),
                             'text' => $this->__('Collections'),
                             'title' => $this->__('Collection list'));
        }
        if (SecurityUtil::checkPermission($this->name . ':Medium:', '::', ACCESS_READ)) {
            $links[] = array('url' => ModUtil::url($this->name, 'user', 'view', array('ot' => 'medium')),
                             'text' => $this->__('Media'),
                             'title' => $this->__('Medium list'));
        }
        return $links;
    }
}
