<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.4 (http://modulestudio.de) at Mon Nov 28 12:34:51 CET 2011.
 */

/**
 * Installer implementation class
 */
class SimpleMedia_Installer extends SimpleMedia_Base_Installer
{
    /**
     * Install the SimpleMedia application.
     *
     * @return boolean True on success, or false.
     */
    public function install()
    {
        // Allowed File extensions, to be done before dir creation
        $this->setVar('allowedExtensions', 'gif, jpeg, jpg, png, pdf, doc, xls, ppt, docx, xlsx, pptx, odt, ods, odp, arj, zip, rar, tar, tgz, gz, bz2, txt, rtf, swf, flv, mp3, mp4, avi, mpg, mpeg, mov');

        // Create the media directories
        $datadir = FileUtil::getDataDirectory().'/SimpleMedia';
        SimpleMedia_Util_Controller::mkdir($datadir . '/media/thefile');
        SimpleMedia_Util_Controller::mkdir($datadir . '/media/thefile/thumbs');
        // Module vars for the media directories, not configurable yet in admin interface
        $this->setVar('mediaDir', 'media/thefile');
        $this->setVar('mediaThumbDir', 'thumbs');
        $this->setVar('mediaThumbExt', '_tmb_');

        // call the parent class
        $result = parent::install();

        $thumbDimensions = array();
        $thumbDimensions[] = array('width' => 80, 'height' => 60);
        $thumbDimensions[] = array('width' => 150, 'height' => 113);
        $thumbDimensions[] = array('width' => 200, 'height' => 150);

        $this->setVar('thumbDimensions', $thumbDimensions);
        
        return $result;
    }
    
    /**
     * Uninstall SimpleMedia.
     *
     * @return boolean True on success, false otherwise.
     */
    public function uninstall()
    {
        // remind user on media upload dir
        $datadir = FileUtil::getDataDirectory().'/SimpleMedia';
        LogUtil::registerStatus($this->__f('The SimpleMedia media upload directories at [%s] can be removed manually', $datadir));

        // call the parent class
        $result = parent::uninstall();

        return $result;
    }
}
