<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ZKM)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Abstract object selector plugin implementation class.
 */
abstract class SimpleMedia_Form_Plugin_AbstractObjectSelector extends SimpleMedia_Form_Plugin_Base_AbstractObjectSelector
{
    // feel free to add your customisation here
}
