<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Geo value input.
 *
 * You can also use all of the features from the Zikula_Form_Plugin_TextInput plugin since
 * the geo input inherits from it.
 */
class SimpleMedia_Form_Plugin_GeoInput extends SimpleMedia_Form_Plugin_Base_GeoInput
{
    // feel free to add your customisation here
}
