<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.1 (http://modulestudio.de).
 */

/**
 * Tree selector.
 *
 * This plugin creates a nested tree selector using a dropdown list.
 * The selected value of the base dropdown list will be set to ID of the selected tree node.
 */
class SimpleMedia_Form_Plugin_TreeSelector extends SimpleMedia_Form_Plugin_Base_TreeSelector
{
    // feel free to add your customisation here
}
