<?php
/**
 * SimpleMedia.
 *
 * @copyright Axel Guckelsberger
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Axel Guckelsberger <info@guite.de>.
 * @link http://zikula.de
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.5.5 (http://modulestudio.de) at Sat Oct 27 20:20:22 CEST 2012.
 */

use Doctrine\ORM\Mapping as ORM;

/**
* Entity extension domain class storing collection categories.
 *
 * This is the base category class for collection entities.
 */
class SimpleMedia_Entity_Base_CollectionCategory extends Zikula_Doctrine2_Entity_EntityCategory
{
    /**
* @ORM\ManyToOne(targetEntity="SimpleMedia_Entity_Collection", inversedBy="categories")
     * @ORM\JoinColumn(name="entityId", referencedColumnName="id")
     * @var SimpleMedia_Entity_Collection
     */
    protected $entity;

    /**
     * Get reference to owning entity.
     *
     * @return SimpleMedia_Entity_Collection
     */
    public function getEntity()
    {
        return $this->entity;
    }

    /**
     * Set reference to owning entity.
     *
     * @param SimpleMedia_Entity_Collection $entity
     */
    public function setEntity(/*SimpleMedia_Entity_Collection */$entity)
    {
        $this->entity = $entity;
    }
}
