<?php
/**
 * SimpleMedia.
 *
 * @copyright Erik Spaan & Axel Guckelsberger (ESP)
 * @license http://www.gnu.org/licenses/lgpl.html GNU Lesser General Public License
 * @package SimpleMedia
 * @author Erik Spaan & Axel Guckelsberger <erik@zikula.nl>.
 * @link https://github.com/zikula-ev/SimpleMedia
 * @link http://zikula.org
 * @version Generated by ModuleStudio 0.6.2 (http://modulestudio.de).
 */

/**
 * Ajax controller class.
 */
class SimpleMedia_Controller_Base_Ajax extends Zikula_Controller_AbstractAjax
{


    /**
     * This method is the default function handling the ajax area called without defining arguments.
     *
     *
     * @return mixed Output.
     */
    public function main()
    {
        // parameter specifying which type of objects we are treating
        $objectType = $this->request->query->filter('ot', 'medium', FILTER_SANITIZE_STRING);
        
        $permLevel = ACCESS_OVERVIEW;
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::', '::', $permLevel), LogUtil::getErrorMsgPermission());
    }
    
    
    /**
     * Retrieve item list for finder selections in Forms, Content type plugin and Scribite.
     *
     * @param string $ot      Name of currently used object type.
     * @param string $sort    Sorting field.
     * @param string $sortdir Sorting direction.
     *
     * @return Zikula_Response_Ajax
     */
    public function getItemListFinder()
    {
        if (!SecurityUtil::checkPermission($this->name . '::Ajax', '::', ACCESS_EDIT)) {
            return true;
        }
        
        $objectType = 'medium';
        if ($this->request->isPost() && $this->request->request->has('ot')) {
            $objectType = $this->request->request->filter('ot', 'medium', FILTER_SANITIZE_STRING);
        } elseif ($this->request->isGet() && $this->request->query->has('ot')) {
            $objectType = $this->request->query->filter('ot', 'medium', FILTER_SANITIZE_STRING);
        }
        $controllerHelper = new SimpleMedia_Util_Controller($this->serviceManager);
        $utilArgs = array('controller' => 'ajax', 'action' => 'getItemListFinder');
        if (!in_array($objectType, $controllerHelper->getObjectTypes('controllerAction', $utilArgs))) {
            $objectType = $controllerHelper->getDefaultObjectType('controllerAction', $utilArgs);
        }
        
        $entityClass = 'SimpleMedia_Entity_' . ucfirst($objectType);
        $repository = $this->entityManager->getRepository($entityClass);
        $repository->setControllerArguments(array());
        $idFields = ModUtil::apiFunc($this->name, 'selection', 'getIdFields', array('ot' => $objectType));
        
        $descriptionField = $repository->getDescriptionFieldName();
        
        $sort = $this->request->request->filter('sort', '', FILTER_SANITIZE_STRING);
        if (empty($sort) || !in_array($sort, $repository->getAllowedSortingFields())) {
            $sort = $repository->getDefaultSortingField();
        }
        
        $sdir = $this->request->request->filter('sortdir', '', FILTER_SANITIZE_STRING);
        $sdir = strtolower($sdir);
        if ($sdir != 'asc' && $sdir != 'desc') {
            $sdir = 'asc';
        }
        
        $where = ''; // filters are processed inside the repository class
        $sortParam = $sort . ' ' . $sdir;
        
        $entities = $repository->selectWhere($where, $sortParam);
        
        $slimItems = array();
        $component = $this->name . ':' . ucfirst($objectType) . ':';
        foreach ($entities as $item) {
            $itemId = '';
            foreach ($idFields as $idField) {
                $itemId .= ((!empty($itemId)) ? '_' : '') . $item[$idField];
            }
            if (!SecurityUtil::checkPermission($component, $itemId . '::', ACCESS_READ)) {
                continue;
            }
            $slimItems[] = $this->prepareSlimItem($objectType, $item, $itemId, $descriptionField);
        }
        
        return new Zikula_Response_Ajax($slimItems);
    }
    
    /**
     * Builds and returns a slim data array from a given entity.
     *
     * @param string $objectType       The currently treated object type.
     * @param object $item             The currently treated entity.
     * @param string $itemid           Data item identifier(s).
     * @param string $descriptionField Name of item description field.
     *
     * @return array The slim data representation.
     */
    protected function prepareSlimItem($objectType, $item, $itemId, $descriptionField)
    {
        $view = Zikula_View::getInstance('SimpleMedia', false);
        $view->assign($objectType, $item);
        $previewInfo = base64_encode($view->fetch('external/' . $objectType . '/info.tpl'));
    
        $title = $item->getTitleFromDisplayPattern();
        $description = ($descriptionField != '') ? $item[$descriptionField] : '';
    
        return array('id'          => $itemId,
                     'title'       => str_replace('&amp;', '&', $title),
                     'description' => $description,
                     'previewInfo' => $previewInfo);
    }
    
    /**
     * Searches for entities for auto completion usage.
     *
     * @param string $ot       Treated object type.
     * @param string $fragment The fragment of the entered item name.
     * @param string $exclude  Comma separated list with ids of other items (to be excluded from search).
     *
     * @return Zikula_Response_Ajax_Plain
     */
    public function getItemListAutoCompletion()
    {
        if (!SecurityUtil::checkPermission($this->name . '::Ajax', '::', ACCESS_EDIT)) {
            return true;
        }
        
        $objectType = 'medium';
        if ($this->request->isPost() && $this->request->request->has('ot')) {
            $objectType = $this->request->request->filter('ot', 'medium', FILTER_SANITIZE_STRING);
        } elseif ($this->request->isGet() && $this->request->query->has('ot')) {
            $objectType = $this->request->query->filter('ot', 'medium', FILTER_SANITIZE_STRING);
        }
        $controllerHelper = new SimpleMedia_Util_Controller($this->serviceManager);
        $utilArgs = array('controller' => 'ajax', 'action' => 'getItemListAutoCompletion');
        if (!in_array($objectType, $controllerHelper->getObjectTypes('controllerAction', $utilArgs))) {
            $objectType = $controllerHelper->getDefaultObjectType('controllerAction', $utilArgs);
        }
        
        $entityClass = 'SimpleMedia_Entity_' . ucfirst($objectType);
        $repository = $this->entityManager->getRepository($entityClass);
        $idFields = ModUtil::apiFunc($this->name, 'selection', 'getIdFields', array('ot' => $objectType));
        
        $fragment = '';
        $exclude = '';
        if ($this->request->isPost() && $this->request->request->has('fragment')) {
            $fragment = $this->request->request->get('fragment', '');
            $exclude = $this->request->request->get('exclude', '');
        } elseif ($this->request->isGet() && $this->request->query->has('fragment')) {
            $fragment = $this->request->query->get('fragment', '');
            $exclude = $this->request->query->get('exclude', '');
        }
        $exclude = ((!empty($exclude)) ? array($exclude) : array());
        
        // parameter for used sorting field
        $sort = $this->request->query->get('sort', '');
        if (empty($sort) || !in_array($sort, $repository->getAllowedSortingFields())) {
            $sort = $repository->getDefaultSortingField();
        }
        $sortParam = $sort . ' asc';
        
        $currentPage = 1;
        $resultsPerPage = 20;
        
        // get objects from database
        list($entities, $objectCount) = $repository->selectSearch($fragment, $exclude, $sortParam, $currentPage, $resultsPerPage);
        
        $out = '<ul>';
        if ((is_array($entities) || is_object($entities)) && count($entities) > 0) {
            $descriptionFieldName = $repository->getDescriptionFieldName();
            $previewFieldName = $repository->getPreviewFieldName();
            foreach ($entities as $item) {
                // class="informal" --> show in dropdown, but do nots copy in the input field after selection
                $itemTitle = $item->getTitleFromDisplayPattern();
                $itemTitleStripped = str_replace('"', '', $itemTitle);
                $itemDescription = isset($item[$descriptionFieldName]) && !empty($item[$descriptionFieldName]) ? $item[$descriptionFieldName] : '';//$this->__('No description yet.');
                $itemId = $item->createCompositeIdentifier();
        
                $out .= '<li id="' . $itemId . '" title="' . $itemTitleStripped . '">';
                $out .= '<div class="itemtitle">' . $itemTitle . '</div>';
                if (!empty($itemDescription)) {
                    $out .= '<div class="itemdesc informal">' . substr($itemDescription, 0, 50) . '&hellip;</div>';
                }
        
                $out .= '</li>';
            }
        }
        $out .= '</ul>';
        
        // return response
        return new Zikula_Response_Ajax_Plain($out);
    }
    
    /**
     * Checks whether a field value is a duplicate or not.
     *
     * @param string $ot Treated object type.
     * @param string $fn Name of field to be checked.
     * @param string $v  The value to be checked for uniqueness.
     * @param string $ex Optional identifier to be excluded from search.
     *
     * @return Zikula_Response_Ajax
     */
    public function checkForDuplicate()
    {
        $this->checkAjaxToken();
        $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::Ajax', '::', ACCESS_EDIT));
        
        $postData = $this->request->request;
        
        $objectType = $postData->filter('ot', 'medium', FILTER_SANITIZE_STRING);
        $controllerHelper = new SimpleMedia_Util_Controller($this->serviceManager);
        $utilArgs = array('controller' => 'ajax', 'action' => 'checkForDuplicate');
        if (!in_array($objectType, $controllerHelper->getObjectTypes('controllerAction', $utilArgs))) {
            $objectType = $controllerHelper->getDefaultObjectType('controllerAction', $utilArgs);
        }
        
        $fieldName = $postData->filter('fn', '', FILTER_SANITIZE_STRING);
        $value = $postData->get('v', '');
        
        if (empty($fieldName) || empty($value)) {
            return new Zikula_Response_Ajax_BadData($this->__('Error: invalid input.'));
        }
        
        // check if the given field is existing and unique
        $uniqueFields = array();
        switch ($objectType) {
            case 'medium':
                    $uniqueFields = array('slug');
                    break;
        }
        if (!count($uniqueFields) || !in_array($fieldName, $uniqueFields)) {
            return new Zikula_Response_Ajax_BadData($this->__('Error: invalid input.'));
        }
        
        $exclude = $postData->get('ex', '');
        $entityClass = 'SimpleMedia_Entity_' . ucfirst($objectType);
        /* can probably be removed
         * $object = new $entityClass();
         */ 
        
        $result = false;
        switch ($objectType) {
        case 'medium':
            $repository = $this->entityManager->getRepository($entityClass);
            switch ($fieldName) {
            case 'slug':
                    $entity = $repository->selectBySlug($value, false, $exclude);
                    $result = ($entity != null && isset($entity['slug']));
                    break;
            }
            break;
        }
        
        // return response
        $result = array('isDuplicate' => $result);
        
        return new Zikula_Response_Ajax($result);
    }
    
        /**
         * Performs different operations on tree hierarchies.
         *
         * @param string $ot        Treated object type.
         * @param string $op        The operation which should be performed (addRootNode, addChildNode, deleteNode, moveNode, moveNodeTo).
         * @param int    $id        Identifier of treated node (not for addRootNode and addChildNode).
         * @param int    $pid       Identifier of parent node (only for addChildNode).
         * @param string $direction The target direction for a move action (only for moveNode [up, down] and moveNodeTo [after, before, bottom]).
         * @param int    $destid    Identifier of destination node for (only for moveNodeTo).
         *
         * @return Zikula_Response_Ajax
         *
         * @throws Zikula_Exception_Ajax_Fatal
         */
        public function handleTreeOperation()
        {
            $this->throwForbiddenUnless(SecurityUtil::checkPermission($this->name . '::Ajax', '::', ACCESS_EDIT));
            
            $postData = $this->request->request;
            
            // parameter specifying which type of objects we are treating
            $objectType = DataUtil::convertFromUTF8($postData->filter('ot', 'collection', FILTER_SANITIZE_STRING));
            // ensure that we use only object types with tree extension enabled
            if (!in_array($objectType, array('collection'))) {
                $objectType = 'collection';
            }
            
            $op = DataUtil::convertFromUTF8($postData->filter('op', '', FILTER_SANITIZE_STRING));
            if (!in_array($op, array('addRootNode', 'addChildNode', 'deleteNode', 'moveNode', 'moveNodeTo'))) {
                throw new Zikula_Exception_Ajax_Fatal($this->__('Error: invalid operation.'));
            }
            
            // Get id of treated node
            $id = 0;
            if (!in_array($op, array('addRootNode', 'addChildNode'))) {
                $id = (int) $postData->filter('id', 0, FILTER_VALIDATE_INT);
                if (!$id) {
                    throw new Zikula_Exception_Ajax_Fatal($this->__('Error: invalid node.'));
                }
            }
            
            $returnValue = array(
                'data'    => array(),
                'message' => ''
            );
            
            $entityClass = 'SimpleMedia_Entity_' . ucfirst($objectType);
            $repository = $this->entityManager->getRepository($entityClass);
            
            $rootId = 1;
            if (!in_array($op, array('addRootNode'))) {
                $rootId = (int) $postData->filter('root', 0, FILTER_VALIDATE_INT);
                if (!$rootId) {
                    throw new Zikula_Exception_Ajax_Fatal($this->__('Error: invalid root node.'));
                }
            }
            
            // Select tree
            $tree = null;
            if (!in_array($op, array('addRootNode'))) {
                $tree = ModUtil::apiFunc($this->name, 'selection', 'getTree', array('ot' => $objectType, 'rootId' => $rootId));
            }
            
            // verification and recovery of tree
            $verificationResult = $repository->verify();
            if (is_array($verificationResult)) {
                foreach ($verificationResult as $errorMsg) {
                    LogUtil::registerError($errorMsg);
                }
            }
            $repository->recover();
            $this->entityManager->clear(); // clear cached nodes
            
            $titleFieldName = $descriptionFieldName = '';
            
            switch ($objectType) {
                case 'collection':
                        $titleFieldName = 'title';
                        $descriptionFieldName = 'title';
                        break;
            }
            
            switch ($op) {
                case 'addRootNode':
                                //$this->entityManager->transactional(function($entityManager) {
                                    $entity = new $entityClass();
                                    $entityData = array();
                                    if (!empty($titleFieldName)) {
                                        $entityData[$titleFieldName] = $this->__('New root node');
                                    }
                                    if (!empty($descriptionFieldName)) {
                                        $entityData[$descriptionFieldName] = $this->__('This is a new root node');
                                    }
                                    $entity->merge($entityData);
                                    
                                
                                    // save new object to set the root id
                                    $action = 'submit';
                                    try {
                                        // execute the workflow action
                                        $workflowHelper = new SimpleMedia_Util_Workflow($this->serviceManager);
                                        $success = $workflowHelper->executeAction($entity, $action);
                                    } catch(\Exception $e) {
                                        LogUtil::registerError($this->__f('Sorry, but an unknown error occured during the %s action. Please apply the changes again!', array($action)));
                                    }
                                //});
            
                                break;
                case 'addChildNode':
                                $parentId = (int) $postData->filter('pid', 0, FILTER_VALIDATE_INT);
                                if (!$parentId) {
                                    throw new Zikula_Exception_Ajax_Fatal($this->__('Error: invalid parent node.'));
                                }
                                
                                //$this->entityManager->transactional(function($entityManager) {
                                    $childEntity = new $entityClass();
                                    $entityData = array();
                                    $entityData[$titleFieldName] = $this->__('New child node');
                                    if (!empty($descriptionFieldName)) {
                                        $entityData[$descriptionFieldName] = $this->__('This is a new child node');
                                    }
                                    $childEntity->merge($entityData);
                                
                                    // save new object
                                    $action = 'submit';
                                    try {
                                        // execute the workflow action
                                        $workflowHelper = new SimpleMedia_Util_Workflow($this->serviceManager);
                                        $success = $workflowHelper->executeAction($childEntity, $action);
                                    } catch(\Exception $e) {
                                        LogUtil::registerError($this->__f('Sorry, but an unknown error occured during the %s action. Please apply the changes again!', array($action)));
                                    }
                                
                                    //$childEntity->setParent($parentEntity);
                                    $parentEntity = ModUtil::apiFunc($this->name, 'selection', 'getEntity', array('ot' => $objectType, 'id' => $parentId, 'useJoins' => false));
                                    if ($parentEntity == null) {
                                        return new Zikula_Response_Ajax_NotFound($this->__('No such item.'));
                                    }
                                    $repository->persistAsLastChildOf($childEntity, $parentEntity);
                                //});
                                $this->entityManager->flush();
                                break;
                case 'deleteNode':
                                // remove node from tree and reparent all children
                                $entity = ModUtil::apiFunc($this->name, 'selection', 'getEntity', array('ot' => $objectType, 'id' => $id, 'useJoins' => false));
                                if ($entity == null) {
                                    return new Zikula_Response_Ajax_NotFound($this->__('No such item.'));
                                }
                                
                                $entity->initWorkflow();
                                
                                // delete the object
                                $action = 'delete';
                                try {
                                    // execute the workflow action
                                        $workflowHelper = new SimpleMedia_Util_Workflow($this->serviceManager);
                                    $success = $workflowHelper->executeAction($entity, $action);
                                } catch(\Exception $e) {
                                    LogUtil::registerError($this->__f('Sorry, but an unknown error occured during the %s action. Please apply the changes again!', array($action)));
                                }
                                
                                $repository->removeFromTree($entity);
                                $this->entityManager->clear(); // clear cached nodes
            
                                break;
                case 'moveNode':
                                $moveDirection = $postData->filter('direction', '', FILTER_SANITIZE_STRING);
                                if (!in_array($moveDirection, array('up', 'down'))) {
                                    throw new Zikula_Exception_Ajax_Fatal($this->__('Error: invalid direction.'));
                                }
                                
                                $entity = ModUtil::apiFunc($this->name, 'selection', 'getEntity', array('ot' => $objectType, 'id' => $id, 'useJoins' => false));
                                if ($entity == null) {
                                    return new Zikula_Response_Ajax_NotFound($this->__('No such item.'));
                                }
                                
                                if ($moveDirection == 'up') {
                                    $repository->moveUp($entity, 1);
                                } else if ($moveDirection == 'down') {
                                    $repository->moveDown($entity, 1);
                                }
                                $this->entityManager->flush();
            
                                break;
                case 'moveNodeTo':
                                $moveDirection = $postData->filter('direction', '', FILTER_SANITIZE_STRING);
                                if (!in_array($moveDirection, array('after', 'before', 'bottom'))) {
                                    throw new Zikula_Exception_Ajax_Fatal($this->__('Error: invalid direction.'));
                                }
                                
                                $destId = (int) $postData->filter('destid', 0, FILTER_VALIDATE_INT);
                                if (!$destId) {
                                    throw new Zikula_Exception_Ajax_Fatal($this->__('Error: invalid destination node.'));
                                }
                                
                                //$this->entityManager->transactional(function($entityManager) {
                                    $entity = ModUtil::apiFunc($this->name, 'selection', 'getEntity', array('ot' => $objectType, 'id' => $id, 'useJoins' => false));
                                    $destEntity = ModUtil::apiFunc($this->name, 'selection', 'getEntity', array('ot' => $objectType, 'id' => $destId, 'useJoins' => false));
                                    if ($entity == null || $destEntity == null) {
                                        return new Zikula_Response_Ajax_NotFound($this->__('No such item.'));
                                    }
                                
                                    if ($moveDirection == 'after') {
                                        $repository->persistAsNextSiblingOf($entity, $destEntity);
                                    } elseif ($moveDirection == 'before') {
                                        $repository->persistAsPrevSiblingOf($entity, $destEntity);
                                    } elseif ($moveDirection == 'bottom') {
                                        $repository->persistAsLastChildOf($entity, $destEntity);
                                    }
                                    $this->entityManager->flush();
                                //});
            
                                break;
            }
            
            $returnValue['message'] = $this->__('The operation was successful.');
            
            // Renew tree
            /** postponed, for now we do a page reload
            $returnValue['data'] = ModUtil::apiFunc($this->name, 'selection', 'getTree', array('ot' => $objectType, 'rootId' => $rootId));
            */
            
            return new Zikula_Response_Ajax($returnValue);
        }
}
